services:
  
  backend_spring:
     #build: ./webchat_agc  
     image: dashshot/webchat_agc:AWScloud
     ports:
      - "443:8443"   
     environment:
        - DATABASE_URL=
        - DATABASE_NAME=
        - AMAZONMQ_RELAYHOST=
        - AMAZONMQ_RELAYPORT=
        - AMAZONMQ_USER=
        - AMAZONMQ_PASS=a
       # #-jwt.secret=your_secret_key_here
 