spring:
  data:
    mongodb:
      username: aitor
      password: aitor
      host: localhost
      port: 27017
      database: chat_app
      authentication-database: admin
      uri: mongodb://aitor:aitor@localhost:27017/chat_app
    
server:
    port: 8080
