version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aitor
      - MONGO_INITDB_ROOT_PASSWORD=aitor

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=aitor
      - ME_CONFIG_MONGODB_ADMINPASSWORD=aitor
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_URL=mongodb://aitor:aitor@mongodb:27017/chat_app?authSource=admin

volumes:
  mongo: {}

#Instalar seguiramente librerias stomp TMB @stomp/stompjs y sockjs-client  // npm install --save @types/sockjs-client